local H = require("tests.helpers")

describe("Data", function()
  local CMM
  before_each(function() CMM = H.Boot() end)

  it("loads the data addon once and reports meta", function()
    assert.is_true(CMM.Data.IsLoaded())
    assert.is_true(CMM.Data.Load())
    assert.equals("fixture", CMM.Data.Meta().version)
  end)

  it("fails cleanly when the data addon is missing", function()
    CMM = H.LoadAddon()
    H.wow.dataLoader = nil
    CMM.Data.Unload()
    assert.is_false(CMM.Data.Load())
    assert.is_nil(CMM.Data.Item(30010))
    assert.same({}, CMM.Data.ItemsForSlot("HEAD"))
  end)

  it("decodes every item field", function()
    local it = CMM.Data.Item(30022)
    assert.equals(30022, it.id)
    assert.equals("Socket Helm", it.name)
    assert.equals(1, it.inv)
    assert.equals(4, it.cls)
    assert.equals(4, it.sub)
    assert.equals(3, it.q)
    assert.equals(110, it.ilvl)
    assert.equals(62, it.req)
    assert.equals(0, it.classmask)
    assert.equals(0, it.flags)
    assert.same({ STA = 20, STR = 20 }, it.stats)
    assert.equals("RY", it.sockets)
    assert.equals(2859, it.sbonus)
    assert.equals(1, it.phase)
    assert.equals("HEAD", it.slot)
    assert.equals(1, #it.src)
    assert.same({ t = "B", npc = 17941, pct = 25 }, it.src[1])
  end)

  it("decodes float stats, class masks, flags and specials", function()
    local w = CMM.Data.Item(30403)
    assert.is_near(80, w.stats.DPS, 1e-9)
    assert.is_near(3.5, w.stats.SPEED, 1e-9)
    assert.equals("MAINHAND", w.slot)
    local idol = CMM.Data.Item(30504)
    assert.equals(1024, idol.classmask)
    assert.same({}, idol.stats)
    local special = CMM.Data.Item(30023)
    assert.is_true(CMM.Data.HasFlag(special, CMM.Constants.FLAG_SPECIAL))
    assert.same({ AP = 40 }, special.special)
    local unique = CMM.Data.Item(30204)
    assert.is_true(CMM.Data.HasFlag(unique, CMM.Constants.FLAG_UNIQUE))
    assert.is_false(CMM.Data.HasFlag(unique, CMM.Constants.FLAG_BOE))
    local heroic = CMM.Data.Item(30012)
    assert.is_true(CMM.Data.HasFlag(heroic, CMM.Constants.FLAG_HEROIC))
  end)

  it("returns the same decoded table on repeated access", function()
    assert.equals(CMM.Data.Item(30010), CMM.Data.Item(30010))
    assert.equals(CMM.Data.Item("30010"), CMM.Data.Item(30010))
  end)

  it("parses every source code", function()
    local S = CMM.Data.ParseSources
    assert.same({ { t = "Q", quest = 10002 } }, S("Q10002"))
    assert.same({ { t = "R", npc = 18678, pct = 9 } }, S("R18678:9"))
    assert.same({ { t = "N", npc = 20000, pct = 3 } }, S("N20000:3"))
    assert.same({ { t = "T", map = 547, pct = 1.5 } }, S("T547:1.5"))
    assert.same({ { t = "G", object = 183000, pct = 16 } }, S("G183000:16"))
    assert.same({ { t = "V", price = 125000, mode = "0" } }, S("V125000:0"))
    assert.same({ { t = "V", price = 0, mode = "E" } }, S("V0:E"))
    assert.same({ { t = "V", price = 0, mode = "H" } }, S("V0:H"))
    assert.same({ { t = "V", price = 500, mode = "A" } }, S("V500:A"))
    assert.same({ { t = "V", price = 0, mode = "0" } }, S("V0:Z")) -- unknown mode -> gold
    assert.same({ { t = "V", price = 150000, mode = "F", faction = 942, rank = 6 } }, S("V150000:F942-6"))
    assert.same({ { t = "K", skillLine = 164, skill = 340 } }, S("K164:340"))
    assert.same({ { t = "W", pct = 0.5 } }, S("W0.5"))
    local multi = S("B17942:5|Q10016|V200000:0")
    assert.equals(3, #multi)
    assert.equals("Q", multi[2].t)
    assert.same({}, S(""))
    assert.same({}, S(nil))
    assert.same({}, S("X123"))
  end)

  it("indexes items by slot and puts one-hand weapons in both weapon slots", function()
    local head = CMM.Data.ItemsForSlot("HEAD")
    assert.is_true(#head >= 30)
    assert.is_true(tContains(head, 30010))
    assert.is_false(tContains(head, 30403))
    local mh = CMM.Data.ItemsForSlot("MAINHAND")
    assert.is_true(tContains(mh, 30403)) -- 2H
    assert.is_true(tContains(mh, 30404)) -- 1H
    assert.is_false(tContains(mh, 30402)) -- OH weapon
    local oh = CMM.Data.ItemsForSlot("OFFHAND")
    assert.is_true(tContains(oh, 30404)) -- 1H
    assert.is_true(tContains(oh, 30402))
    assert.is_true(tContains(oh, 30405)) -- shield
    assert.is_true(tContains(oh, 30406)) -- held
    assert.is_false(tContains(oh, 30403))
    local ranged = CMM.Data.ItemsForSlot("RANGED")
    assert.is_true(tContains(ranged, 30501) and tContains(ranged, 30502) and tContains(ranged, 30504))
    assert.is_true(tContains(CMM.Data.ItemsForSlot("CHEST"), 30602)) -- inv 20 robe
    assert.same({}, CMM.Data.ItemsForSlot("NOPE"))
  end)

  it("decodes quests with faction shorthands and reward lists", function()
    local q = CMM.Data.Quest(10002)
    assert.equals("Chain A3", q.title)
    assert.equals(58, q.minLevel)
    assert.equals(62, q.questLevel)
    assert.equals(CMM.Constants.ALLIANCE_MASK, q.races)
    assert.equals(0, q.classes)
    assert.equals(3521, q.zone)
    assert.equals(0, q.type)
    assert.equals(10001, q.prev)
    assert.same({ 30001, 30002 }, q.choice)
    assert.same({}, q.fixed)
    assert.equals(CMM.Constants.HORDE_MASK, CMM.Data.Quest(10010).races)
    assert.equals(16, CMM.Data.Quest(10011).classes)
    assert.same({ 30030 }, CMM.Data.Quest(10017).fixed)
    assert.equals(81, CMM.Data.Quest(9738).type)
    assert.is_nil(CMM.Data.Quest(1))
  end)

  it("decodes npcs, bosses, dungeons and objects", function()
    local npc = CMM.Data.Npc(18678)
    assert.same({ entry = 18678, name = "Fulgorge", level = 64, rank = 2, map = 530, respawnMin = 180 }, npc)
    local boss = CMM.Data.Boss(19895)
    assert.same({ entry = 19895, map = 547, index = 1, heroic = true }, boss)
    assert.is_false(CMM.Data.Boss(17991).heroic)
    local d = CMM.Data.Dungeon(547)
    assert.equals("The Slave Pens", d.name)
    assert.same({ 17941, 17991, 17942 }, d.bosses)
    assert.same({ entry = 183000, name = "Coilfang Chest", map = 547 }, CMM.Data.Object(183000))
    local list = CMM.Data.Dungeons()
    assert.equals(2, #list)
    assert.equals(543, list[1].map) -- sorted by min level then name
  end)

  it("resolves zone names through the client first, then the pack", function()
    assert.equals("Zangarmarsh", CMM.Data.ZoneName(3521))
    H.wow.areaNames = { [3521] = "Zangarmarsch" }
    assert.equals("Zangarmarsch", CMM.Data.ZoneName(3521))
    H.wow.areaNames = nil
    assert.is_nil(CMM.Data.ZoneName(0))
    assert.is_nil(CMM.Data.ZoneName(99999))
  end)

  it("prefers the client's localized item name", function()
    assert.equals("Boss Helm", CMM.Data.ItemName(30010))
    H.wow.items[30010] = { name = "Bosshelm" }
    assert.equals("Bosshelm", CMM.Data.ItemName(30010))
    assert.equals("item:1", CMM.Data.ItemName(1))
  end)
end)
