local H = require("tests.helpers")

describe("Obtain", function()
  local CMM, O, player
  local opts = { lookahead = 2, phase = 5 }
  local function item(id) return CMM.Data.Item(id) end

  before_each(function()
    CMM = H.Boot()
    O = CMM.Obtain
    player = CMM.Player.Get()
  end)

  describe("Gate", function()
    it("passes a plain boss drop", function()
      assert.is_true(O.Gate(item(30010), player, opts))
    end)
    it("rejects the wrong class mask", function()
      local ok, why = O.Gate(item(30026), player, opts)
      assert.is_false(ok)
      assert.equals("class", why)
    end)
    it("rejects unusable armor and weapon types", function()
      local ok, why = O.Gate(item(30504), player, opts) -- idol, druid only
      assert.is_false(ok)
      assert.equals("class", why)
      H.wow.player.class, H.wow.player.classToken = "Priest", "PRIEST"
      CMM.Player.Refresh()
      ok, why = O.Gate(item(30010), CMM.Player.Get(), opts) -- plate
      assert.is_false(ok)
      assert.equals("armor", why)
      ok, why = O.Gate(item(30403), CMM.Player.Get(), opts) -- 2H sword
      assert.is_false(ok)
      assert.equals("weapon", why)
    end)
    it("rejects items above level + lookahead", function()
      local ok, why = O.Gate(item(30006), player, opts) -- req 66, quest min 66
      assert.is_false(ok)
      assert.equals("level", why)
      assert.is_true(O.Gate(item(30006), player, { lookahead = 4, phase = 5 }))
      -- item level ok but the quest's minimum level still gates
      CasualMinMaxer_Data.items[30036] = "Early Helm;1;4;4;3;100;60;0;0;STA:1;;0;1"
      CasualMinMaxer_Data.src[30036] = "Q10013"
      local ok2, why2 = O.Gate(item(30036), player, opts)
      assert.is_false(ok2)
      assert.equals("level", why2)
    end)
    it("rejects items flagged for the other faction", function()
      assert.is_true(O.Gate(item(30033), player, opts))
      local ok, why = O.Gate(item(30034), player, opts)
      assert.is_false(ok)
      assert.equals("faction", why)
      H.wow.player.faction = "Horde"
      H.wow.player.race, H.wow.player.raceToken = "Orc", "Orc"
      CMM.Player.Refresh()
      assert.is_true(O.Gate(item(30034), CMM.Player.Get(), opts))
      ok, why = O.Gate(item(30033), CMM.Player.Get(), opts)
      assert.is_false(ok)
      assert.equals("faction", why)
    end)

    it("rejects the wrong faction and class for quests", function()
      local ok, why = O.Gate(item(30003), player, opts)
      assert.is_false(ok)
      assert.equals("race", why)
      ok, why = O.Gate(item(30004), player, opts)
      assert.is_false(ok)
      assert.equals("class", why)
    end)
    it("rejects completed quests and raid quests", function()
      H.wow.player.completedQuests[10015] = true
      CMM.Player.InvalidateQuests()
      local ok, why = O.Gate(item(30008), player, opts)
      assert.is_false(ok)
      assert.equals("done", why)
      ok, why = O.Gate(item(30007), player, opts)
      assert.is_false(ok)
      assert.equals("raid", why)
    end)
    it("rejects content too high and dungeons above lookahead", function()
      local ok, why = O.Gate(item(30027), player, opts) -- mob level 70
      assert.is_false(ok)
      assert.equals("content level", why)
      H.wow.player.level = 50
      CMM.Player.Refresh()
      ok, why = O.Gate(item(30035), CMM.Player.Get(), opts) -- req 45, Slave Pens trash, dungeon min 55
      assert.is_false(ok)
      assert.equals("dungeon level", why)
      assert.is_true(O.Gate(item(30035), CMM.Player.Get(), { lookahead = 5, phase = 5 }))
    end)
    it("rejects later content phases", function()
      local p70 = { level = 70, class = "WARRIOR", classMask = 1, raceMask = 1, professions = {}, usable = player.usable }
      local ok, why = O.Gate(item(30025), p70, { lookahead = 0, phase = 4 })
      assert.is_false(ok)
      assert.equals("phase", why)
    end)
    it("gates heroic-only items and heroic bosses to level 70", function()
      local ok, why = O.Gate(item(30012), player, { lookahead = 10, phase = 5 })
      assert.is_false(ok)
      assert.equals("heroic", why)
      H.wow.player.level = 70
      CMM.Player.Refresh()
      assert.is_true(O.Gate(item(30012), CMM.Player.Get(), opts))
    end)
    it("gates reputation vendors only when the standing is known and too low", function()
      assert.is_true(O.Gate(item(30018), player, opts)) -- unknown faction: allowed
      H.wow.player.factions[942] = 5 -- honored, needs revered (6)
      local ok, why = O.Gate(item(30018), player, opts)
      assert.is_false(ok)
      assert.equals("reputation", why)
      H.wow.player.factions[942] = 6
      assert.is_true(O.Gate(item(30018), player, opts))
    end)
    it("passes when at least one source is usable", function()
      H.wow.player.completedQuests[10016] = true
      CMM.Player.InvalidateQuests()
      assert.is_true(O.Gate(item(30031), player, opts))
    end)
  end)

  describe("ChainRemaining", function()
    it("counts uncompleted quests back to the chain start", function()
      local steps, first = O.ChainRemaining(10002, player)
      assert.equals(3, steps)
      assert.equals(10000, first)
    end)
    it("subtracts completed prerequisites", function()
      H.wow.player.completedQuests[10000] = true
      CMM.Player.InvalidateQuests()
      local steps, first = O.ChainRemaining(10002, player)
      assert.equals(2, steps)
      assert.equals(10001, first)
      H.wow.player.completedQuests[10001] = true
      CMM.Player.InvalidateQuests()
      assert.equals(1, O.ChainRemaining(10002, player))
    end)
    it("handles single quests and cycles", function()
      assert.equals(1, O.ChainRemaining(10016, player))
      assert.equals(0, O.ChainRemaining(1, player))
      CasualMinMaxer_Data.quests[10020] = "Loop A;58;60;0;0;3521;0;10021;0;0;;"
      CasualMinMaxer_Data.quests[10021] = "Loop B;58;60;0;0;3521;0;10020;0;0;;"
      assert.equals(2, O.ChainRemaining(10020, player))
    end)
  end)

  describe("Evaluate", function()
    local T = CMM and CMM.Constants.TIER
    before_each(function() T = CMM.Constants.TIER end)

    it("tier 1 quest in the current zone, with chain steps", function()
      local e = O.Evaluate(item(30001), player, opts)
      assert.equals(1, e.tier)
      assert.equals(3 * T.minutesPerQuest, e.minutes)
      assert.equals("Quest, 3 steps left, Zangarmarsh", e.text)
      assert.is_false(e.group)
      assert.equals(3521, e.zone)
    end)
    it("adds travel time when the quest zone differs", function()
      local e = O.Evaluate(item(30009), player, opts)
      assert.equals(1, e.tier)
      assert.equals(T.minutesPerQuest + T.travel, e.minutes)
      assert.equals("Quest, Hellfire Peninsula", e.text)
    end)
    it("tier 2 for dungeon and group quests", function()
      local e = O.Evaluate(item(30701), player, opts) -- Lost in Action, 2-step chain
      assert.equals(2, e.tier)
      assert.equals(T.groupOverhead + 2 * T.minutesPerQuest, e.minutes)
      assert.equals("Dungeon quest, 2 steps left, Coilfang Reservoir", e.text)
      assert.is_true(e.group)
      local g = O.Evaluate(item(30005), player, opts)
      assert.equals(2, g.tier)
      assert.equals("Group quest, Hellfire Peninsula", g.text)
    end)
    it("tier 3 boss drop uses time to boss and drop chance", function()
      local e = O.Evaluate(item(30010), player, opts) -- Rokmar, boss 2, t=15, 20 %
      assert.equals(3, e.tier)
      assert.is_near((T.groupOverhead + 15) / 0.2, e.minutes, 1e-9)
      assert.equals("Boss 2 of 3, 20%, The Slave Pens", e.text)
      assert.equals(547, e.map)
      assert.equals(17991, e.boss)
    end)
    it("tier 4 for low boss chance, rare, named, trash, world and chest below 15", function()
      local e = O.Evaluate(item(30011), player, opts) -- Quagmirran 5 %
      assert.equals(4, e.tier)
      assert.is_near((T.groupOverhead + 25) / 0.05, e.minutes, 1e-9)
      local r = O.Evaluate(item(30013), player, opts) -- Fulgorge respawn 180, 9 %
      assert.equals(4, r.tier)
      assert.is_near(180 / 0.09, r.minutes, 1e-9)
      assert.equals("Rare spawn, 9.0%, Fulgorge", r.text)
      local r2 = O.Evaluate(item(30032), player, opts) -- respawn 120 -> max(120, 30)
      assert.is_near(120 / 0.12, r2.minutes, 1e-9)
      assert.is_true(r2.group)
      local n = O.Evaluate(item(30014), player, opts)
      assert.equals(4, n.tier)
      assert.is_near(T.namedMinutes / 0.03, n.minutes, 1e-9)
      assert.equals("Mob drop, 3.0%, Durn the Hungerer", n.text)
      local t = O.Evaluate(item(30015), player, opts)
      assert.equals(4, t.tier)
      assert.is_near(T.trashRun / 0.015, t.minutes, 1e-9)
      assert.equals("Trash, 1.5%, The Slave Pens", t.text)
      local w = O.Evaluate(item(30021), player, opts)
      assert.equals(4, w.tier)
      assert.is_near(T.namedMinutes / 0.005, w.minutes, 1e-9)
      assert.equals("World drop, 0.5%", w.text)
    end)
    it("tier 3 chest at 16 %", function()
      local e = O.Evaluate(item(30016), player, opts)
      assert.equals(3, e.tier)
      assert.is_near((T.groupOverhead + 8) / 0.16, e.minutes, 1e-9)
      assert.equals("Chest, 16%, The Slave Pens", e.text)
    end)
    it("tier 5 vendors and crafted by others; tier 1 for own profession", function()
      local v = O.Evaluate(item(30017), player, opts)
      assert.equals(5, v.tier)
      assert.equals(T.vendorWalk, v.minutes)
      assert.equals("Vendor, 12g 50s", v.text)
      local p70 = { level = 70, class = "WARRIOR", classMask = 1, raceMask = 1, professions = {}, usable = player.usable, zoneName = "" }
      local ext = O.Evaluate(item(30020), p70, opts)
      assert.equals("Vendor, badges or honor", ext.text)
      local rep = O.Evaluate(item(30018), player, opts)
      assert.equals("Reputation vendor, Revered, 15g 0s", rep.text)
      local k = O.Evaluate(item(30019), player, opts) -- needs BS 340, player has 300
      assert.equals(5, k.tier)
      assert.equals(T.craftOther, k.minutes)
      assert.equals("Crafted, Blacksmithing 340", k.text)
      H.wow.player.skills = { { "Blacksmithing", 350, 375 } }
      CMM.Player.Refresh()
      local own = O.Evaluate(item(30019), CMM.Player.Get(), opts)
      assert.equals(1, own.tier)
      assert.equals(T.craftOwn, own.minutes)
    end)
    it("picks the fastest usable source", function()
      local e = O.Evaluate(item(30031), player, opts) -- boss 5 %, quest other zone, vendor
      assert.equals("V", e.src.t)
      assert.equals(5, e.tier)
      local e2 = O.Evaluate(item(30031), player, { lookahead = 2, phase = 5, sourceFilter = function(s) return s.t ~= "V" end })
      assert.equals("Q", e2.src.t)
      assert.equals(1, e2.tier)
      local e3 = O.Evaluate(item(30031), player, { lookahead = 2, phase = 5, sourceFilter = function(s) return s.t == "B" end })
      assert.equals(4, e3.tier)
      assert.is_nil(O.Evaluate(item(30031), player, { lookahead = 2, phase = 5, sourceFilter = function() return false end }))
    end)
    it("labels heroic bosses", function()
      H.wow.player.level = 70
      CMM.Player.Refresh()
      local e = O.Evaluate(item(30012), CMM.Player.Get(), opts)
      assert.equals(3, e.tier)
      assert.matches("^Heroic boss 2 of 3, 20%%", e.text)
    end)
    it("honors constant overrides from the account DB", function()
      CasualMinMaxerDB.constants.minutesPerQuest = 4
      local e = O.Evaluate(item(30001), player, opts)
      assert.equals(12, e.minutes)
    end)
  end)

  describe("LastsUntil", function()
    it("returns the level where a guaranteed item overtakes the candidate", function()
      local ctx = H.Ctx(CMM, "HEAD")
      -- Boss Helm (STA 28, STR 26, HIT 10) vs guaranteed High Level Helm (STA 40, STR 40, req 66)
      assert.equals(66, O.LastsUntil(item(30010), "HEAD", ctx, player))
      -- the strongest helm has nothing guaranteed above it
      assert.equals(70, O.LastsUntil(item(30025), "HEAD", ctx, player))
    end)
    it("ignores quests the character cannot take", function()
      H.wow.player.completedQuests[10013] = true
      CMM.Player.InvalidateQuests()
      local ctx = H.Ctx(CMM, "HEAD")
      assert.equals(70, O.LastsUntil(item(30010), "HEAD", ctx, player))
    end)
    it("counts crafted items from an own profession", function()
      H.wow.player.skills = { { "Blacksmithing", 375, 375 } }
      CMM.Player.Refresh()
      local ctx = H.Ctx(CMM, "HEAD")
      -- Crafted Helm STA 26 STR 26 beats Travel Helm STA 18 STR 18 at level 63 already
      assert.equals(63, O.LastsUntil(item(30009), "HEAD", ctx, CMM.Player.Get()))
    end)
  end)
end)
