-- Generated by pipeline/build.py. Do not edit.
CasualMinMaxer_Data = CasualMinMaxer_Data or {}
local D = CasualMinMaxer_Data
D.items, D.src, D.quests, D.npcs, D.bosses, D.dungeons, D.objects, D.zones, D.specials = {}, {}, {}, {}, {}, {}, {}, {}, {}
D.meta = { version = "dev", built = "2026-09-19", dbVersion = "tbc-db", items = 8765, quests = 2904, phases = 5 }
